stages:
  - build
  - deploy
  - logs

build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнера для проверки его содержимого..."
    - docker-compose -f infrastructure/docker-compose.yaml up
    - echo "Просмотр структуры файлов в контейнере web..."
    - docker exec -i bearcoder-web ls -R /
    - echo "Поиск всех файлов в контейнере web..."
    - docker exec -i bearcoder-web find /
    - echo "Просмотр логов контейнера web..."
    - docker logs bearcoder-web || echo "Логи не найдены"
    - echo "Информация о контейнере web..."
    - docker exec -i bearcoder-web ps aux || echo "Команда ps не найдена"
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Просмотр состояния Docker системы..."
    - docker info
  only:
    - develop  # Поменяли на 'develop' для всех веток

deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
  needs:
    - build-jobs  # Убедитесь, что build-jobs завершен успешно перед deploy
  only:
    - develop

logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
