stages:
  - build
  - migrate
  - deploy
  - logs

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop

# Стейдж для миграции базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Удаляем старые volumes..."
    - docker-compose -f infrastructure/docker-compose.yaml down -v

    - echo "Сборка образов и запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - docker-compose -f infrastructure/docker-compose.yaml up -d

    # Ждём, пока база данных полностью запустится
    - echo "Ждём, пока база данных станет доступной..."
    - sleep 10

    # Применяем миграции Django
    - echo "Применение миграций Django..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py makemigrations
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate

    - echo "Миграции завершены!"
  needs:
    - build-jobs
  only:
    - develop

# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  needs:
    - migrate-jobs
  only:
    - develop

# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
