stages:
  - build
  - migrate
  - deploy
  - logs

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Сборка образов с обновлением только изменений..."
    - docker-compose -f infrastructure/docker-compose.yaml build --no-cache web
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop

# Стейдж для миграций базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Применение миграций Django..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py makemigrations --no-input
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate --no-input
    - echo "Миграции завершены!"
  needs:
    - build-jobs
  only:
    - develop

# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Обновление контейнеров без полного пересоздания..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d --no-recreate
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  needs:
    - migrate-jobs
  only:
    - develop

# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
