stages:
  - build
  - deploy
  - test
  - logs

before_script:
  - echo "Проверка прав доступа и Docker..."
  - docker info
  - docker-compose --version || curl -sSL https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнера для проверки его содержимого..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Просмотр структуры файлов в контейнере web..."
    - docker exec -i bearcoder-web ls -R /
    - echo "Поиск всех файлов в контейнере web..."
    - docker exec -i bearcoder-web find /
    - echo "Просмотр логов контейнера web..."
    - docker logs bearcoder-web || echo "Логи не найдены"
    - echo "Информация о контейнере web..."
    - docker exec -i bearcoder-web ps aux || echo "Команда ps не найдена"
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Просмотр состояния Docker системы..."
    - docker info
  only:
    - develop

deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
  only:
    - develop

