stages:
  - fetch-code
  - build
  - migrate
  - deploy
  - logs

# Стейдж для клонирования кода
fetch-code:
  stage: fetch-code
  script:
    - echo "Удаление старой версии проекта..."
    - rm -rf ./bearcoderr
    - echo "Клонирование свежего кода из GitLab..."
    - git clone https://gitlab+deploy-token-6716584:gldt-2aLUUuThX-DDeJb1uCCt@gitlab.com/bearcoder1/bearcoderr.git ./bearcoderr
  only:
    - develop

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Сборка Docker образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
  needs:
    - fetch-code
  only:
    - develop

# Стейдж для миграции базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Запуск контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d

    # Ожидание полной инициализации контейнеров
    - echo "Ожидание запуска контейнеров..."
    - |
      until docker-compose -f infrastructure/docker-compose.yaml ps | grep bearcoder-web | grep "Up"; do
        echo "Контейнер bearcoder-web ещё не запущен, ждём..."
        sleep 5
      done

    - echo "Контейнер bearcoder-web запущен, применяем миграции..."
    - docker-compose -f infrastructure/docker-compose.yaml exec web poetry run python manage.py makemigrations --check
    - docker-compose -f infrastructure/docker-compose.yaml exec web poetry run python manage.py migrate
  needs:
    - build-jobs
  only:
    - develop


# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Обновление контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
  needs:
    - migrate-jobs
  only:
    - develop

# Стейдж для просмотра логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Просмотр состояния контейнеров..."
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  needs:
    - deploy-jobs
  only:
    - develop
