stages:
  - build
  - migrate
  - import_data
  - deploy
  - logs

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop

# Стейдж для миграций базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Применение миграций Django..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate
    - echo "Миграции завершены!"
  needs:
    - build-jobs
  only:
    - develop

# Стейдж для импорта данных из бекапа
import-data-jobs:
  stage: import_data
  script:
    - echo "Импорт данных из бекапа..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm import_db
    - echo "Данные успешно импортированы!"
  needs:
    - migrate-jobs
  only:
    - develop

# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  needs:
    - import-data-jobs
  only:
    - develop

# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
