stages:
  - build
  - migrate
  - import_data
  - deploy
  - logs

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop

# Стейдж для миграций базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Применение миграций Django..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate
    - echo "Миграции завершены!"
  needs:
    - build-jobs
  only:
    - develop

# Стейдж для импорта данных в базу
import-data-jobs:
  stage: import_data
  script:
    - echo "Подключение к базе данных и импорт данных из бекапа..."
    - docker-compose -f infrastructure/docker-compose.yaml exec -T db psql -U docdevuserdb -d docdevdatabase -f /backup/backup.sql
    - echo "Данные успешно импортированы!"
  needs:
    - migrate-jobs
  only:
    - develop
  # Предполагается, что бекап находится в /backup в контейнере
  # Если бекап находится на хосте, вам нужно будет сначала копировать его в контейнер
  before_script:
    - echo "Копирование бекапа в контейнер..."
    - docker cp ./backup.sql $(docker-compose -f infrastructure/docker-compose.yaml ps -q db):/backup/backup.sql

# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  needs:
    - import-data-jobs
  only:
    - develop

# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
