image: docker:20.10.16 # Используем образ с Docker для CI

services:
  - docker:20.10.16-dind  # Сервис для Docker-in-Docker, чтобы работать с Docker внутри контейнера

stages:
  - build
  - deploy
  - test
  - logs

before_script:
  - echo "Проверка прав доступа и Docker..."
  - docker info || echo "Docker не доступен"
  - docker-compose --version || echo "docker-compose не установлен"

build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнера для проверки его содержимого..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Просмотр структуры файлов в контейнере web..."
    - docker exec -i bearcoder-web ls -R /
    - echo "Поиск всех файлов в контейнере web..."
    - docker exec -i bearcoder-web find /
    - echo "Просмотр логов контейнера web..."
    - docker logs bearcoder-web || echo "Логи не найдены"
    - echo "Информация о контейнере web..."
    - docker exec -i bearcoder-web ps aux || echo "Команда ps не найдена"
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Просмотр состояния Docker системы..."
    - docker info
  only:
    - develop

deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
  only:
    - develop
