stages:
  - build
  - deploy
  - deploy-database
  - logs

build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop

deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
  needs:
    - build-jobs
  only:
    - develop

deploy-database:
  stage: deploy-database
  image: postgres:16-alpine
  variables:
    PGPASSWORD: $POSTGRES_PASSWORD  # Устанавливаем пароль для PostgreSQL
  script:
    - echo "Загрузка дампа базы данных..."
    # Копируем файл дампа в контейнер
    - docker cp backup.sql bearcoder-db:/tmp/backup.sql
    # Выполняем импорт данных из дампа в базу данных
    - docker exec -i bearcoder-db psql -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/backup.sql
  dependencies:
    - build-jobs
  only:
    - develop




logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
