stages:
  - fetch-code
  - build
  - migrate
  - deploy
  - logs

fetch-code:
  stage: fetch-code
  script:
    - echo "Удаляем старую папку bearcoderr..."
    - rm -rf ./bearcoderr
    - echo "Клонируем код..."
    - git clone https://gitlab+deploy-token-6716584:gldt-2aLUUuThX-DDeJb1uCCt@gitlab.com/bearcoder1/bearcoderr.git ./bearcoderr
    - cd ./bearcoderr/api
    - ls -la
  only:
    - develop


# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop

# Стейдж для миграций базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Применение миграций Django..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py makemigrations
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate
    - echo "Миграции завершены!"
  needs:
    - build-jobs
  only:
    - develop

# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  needs:
    - migrate-jobs
  only:
    - develop


# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
