stages:
  - build
  - migrate
  - deploy
  - logs


# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop



# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых изменений..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d --no-build
    - echo "Обновлены контейнеры без пересоздания образов."
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  needs:
    - migrate-jobs
  only:
    - develop


# Стейдж для миграций базы данных
migrate-jobs:
  stage: migrate
  script:
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate --no-input
  only:
    - develop


# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
