stages:
  - build
  - migrate
  - deploy
  - logs

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Информация о Docker:"
    - docker info
  only:
    - develop

# Стейдж для создания и применения миграций базы данных
migrate-jobs:
  stage: migrate
  script:
    - echo "Установка зависимостей..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web bash -c "poetry install"
    - echo "Создание миграций..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web bash -c "poetry run python manage.py makemigrations models --noinput"
    - echo "Применение миграций..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web bash -c "poetry run python manage.py migrate models"
  needs:
    - build-jobs
  only:
    - develop

# Стейдж деплоя контейнеров
deploy-jobs:
  stage: deploy
  script:
    - echo "Деплой новых контейнеров..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d --build
    - echo "Проверка состояния контейнеров после деплоя..."
    - docker ps -a
    - echo "Информация о Docker:"
    - docker info
    - docker-compose -f infrastructure/docker-compose.yaml run web poetry run python manage.py makemigrations
    - docker-compose -f infrastructure/docker-compose.yaml run web poetry run python manage.py migrate
  needs:
    - migrate-jobs
  only:
    - main

# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Статус контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
