stages:
  - build
  - deploy
  - migrate
  - import_db
  - logs

# Стейдж сборки Docker образов
build-jobs:
  stage: build
  script:
    - echo "Очистка старых Docker данных для освобождения места..."
    - docker system prune -af --volumes
    - echo "Сборка образов..."
    - docker-compose -f infrastructure/docker-compose.yaml build
    - echo "Запуск контейнеров для проверки..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d
    - echo "Проверка состояния контейнеров после сборки..."
    - docker ps -a
    - echo "Docker система:"
    - docker info
  only:
    - develop



# Стейдж деплоя контейнеров и очистки базы данных
deploy-jobs:
  stage: deploy
  script:
    - echo "Очистка базы данных перед деплоем..."
    - docker-compose -f infrastructure/docker-compose.yaml exec -T bearcoder-db psql -U bearcoderr_user -d bearcoderr -c "DROP SCHEMA public CASCADE;"
    - docker-compose -f infrastructure/docker-compose.yaml exec -T bearcoder-db psql -U bearcoderr_user -d bearcoderr -c "CREATE SCHEMA public;"
    - echo "База данных очищена!"

    - echo "Деплой новых изменений..."
    - docker-compose -f infrastructure/docker-compose.yaml up -d --no-build
    - echo "Обновлены контейнеры без пересоздания образов."

  needs:
    - migrate-jobs
  only:
    - develop

# Стейдж для миграции базы данных
migrate:
  stage: deploy
  script:
    - echo "Применение миграций Django к базе данных..."
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py makemigrations --no-input
    - docker-compose -f infrastructure/docker-compose.yaml run --rm web poetry run python manage.py migrate --no-input --database=default
    - echo "Миграции завершены!"

  needs:
    - build-jobs
  only:
    - develop


# Стейдж для импорта базы данных из дампа
import_db:
  stage: deploy
  script:
    - echo "Импорта базы данных из дампа..."
    - docker cp bearcoder-db:/mnt/data/bearcoderr_database.dump ./bearcoderr_database.dump
    - docker exec -i bearcoder-db psql -U bearcoderr_user -d bearcoderr < ./bearcoderr_database.dump
    - echo "Дамп базы данных успешно импортирован!"

  needs:
    - deploy-jobs
  only:
    - develop

# Стейдж для логов контейнеров
logs-jobs:
  stage: logs
  script:
    - echo "Состояние контейнеров:"
    - docker ps -a
    - echo "Логи контейнера web:"
    - docker logs bearcoder-web
    - echo "Логи контейнера db:"
    - docker logs bearcoder-db
  only:
    - develop
