# Generated by Django 5.1.4 on 2024-12-17 09:20

import ckeditor.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
import src.apps.settings.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFormsHome', models.CharField(max_length=200, verbose_name='Имя отправителя')),
                ('emailFormsHome', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('callFormsHome', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10)),
                ('massageFormsHome', models.TextField(verbose_name='Сообщение')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='GallerySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleGallery', models.CharField(help_text='Не больше 200 символов', max_length=200, verbose_name='Название страницы с фотографиями')),
                ('slugGallery', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('dataGallery', models.DateField(default=datetime.date.today, verbose_name='Дата поездки')),
                ('contentGallery', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент для галереи')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgnews', models.ImageField(upload_to='photos/news/', verbose_name='Главное изображение записи')),
                ('dataNews', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('countView', models.IntegerField(default=0, verbose_name='Сортировка для последних новостей')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время публикации')),
                ('titlenews', models.CharField(max_length=500, verbose_name='Название статьи')),
                ('slugnews', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Заполняется автоматически')),
                ('contentnews', ckeditor.fields.RichTextField(verbose_name='Контент Блог')),
                ('imgPostMini', models.ImageField(blank=True, null=True, upload_to='photos/news/', verbose_name='Изображение мини поста')),
                ('contentPostMini', models.TextField(blank=True, max_length=500, null=True, verbose_name='Контент поста')),
                ('text_twitter', models.TextField(blank=True, max_length=200, null=True, verbose_name='Текст для твиттера')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='newsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCategory', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slagCategory', models.SlugField(blank=True, max_length=500, null=True, verbose_name='Ссылка на категорию')),
                ('contentCategory', models.TextField(max_length=500, verbose_name='Контент категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='newsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTag', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slagTag', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Ссылка на тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ServicesSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgServices', models.ImageField(upload_to='media/services/', verbose_name='Главное изображение')),
                ('titleServices', models.CharField(max_length=200, verbose_name='Название направления')),
                ('exeptServices', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('contentServices', ckeditor.fields.RichTextField(verbose_name='Контент услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgHome', models.ImageField(upload_to='media/photos/home/', verbose_name='Главное изображение')),
                ('logoSite', models.ImageField(upload_to='media/photos/', verbose_name='Логотип сайта')),
                ('favSite', models.ImageField(upload_to='media/photos/', verbose_name='Фавикон сайта')),
                ('titleHome', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('buttonHeader', models.CharField(max_length=500, verbose_name='Название кнопки')),
                ('sub_titleHome', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('textHome', models.TextField(default='Привет', verbose_name='Подзаголовок')),
                ('copyText', models.CharField(max_length=500, verbose_name='Текст копирайта')),
                ('admin_email', models.EmailField(default='bearcoderr@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Formsnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComm', models.CharField(max_length=500, verbose_name='Имя')),
                ('emailComm', models.EmailField(max_length=500, verbose_name='Email')),
                ('textComm', models.TextField(verbose_name='Сообщение')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время отправки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий к Блог',
                'verbose_name_plural': 'Комментарии к новостям',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.newscategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='models.newstag', verbose_name='Теги статьи'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='models.gallerysite')),
            ],
        ),
        migrations.CreateModel(
            name='numberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberTitle', models.CharField(max_length=500, verbose_name='Впишите число или текст')),
                ('numberText', models.CharField(max_length=500, verbose_name='Напишите текст')),
                ('numberDopSimvol', models.CharField(max_length=500, verbose_name='Доп символ после цифры')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.settings')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='MenuSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLink', models.TextField(default='#', verbose_name='Название ссылки в меню')),
                ('link', models.TextField(default='#', verbose_name='Ссылка на блок на сайте')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.settings')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='experienceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearExperience', models.DateField(default=None, verbose_name='Год начала карьеры')),
                ('year_old_Experience', models.DateField(blank=True, default=None, null=True, verbose_name='Год окончания карьеры')),
                ('postExperience', models.CharField(max_length=500, verbose_name='Название должности')),
                ('companyExperience', models.CharField(max_length=500, verbose_name='Компания')),
                ('textExperience', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.settings')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='contactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSontact', models.CharField(max_length=500, verbose_name='Название пункта с контактами')),
                ('titleSontact', models.CharField(max_length=500, verbose_name='Номер телефона/почта/адрес')),
                ('linkSontact', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('imgSontact', models.CharField(help_text='Ссылка на шрифтовой пак https://fontawesome.ru/', max_length=500, verbose_name='Класс по каторому будет показана иконка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.settings')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='skillsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleSkills', models.CharField(max_length=500, verbose_name='Название')),
                ('countSkills', models.PositiveIntegerField(verbose_name='Проценты')),
                ('imgSkills', src.apps.settings.fields.SVGImageField(upload_to='photos/home/skill/', verbose_name='Иконка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.settings')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='socialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altSocial', models.CharField(max_length=500, verbose_name='Название соц. сети')),
                ('lincSocial', models.URLField(max_length=1000)),
                ('classSocial', models.CharField(help_text='Ссылка на шрифтовой пак https://fontawesome.ru/', max_length=500, verbose_name='Класс по каторому будет показана иконка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.settings')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
