# Generated by Django 5.1.3 on 2024-11-21 12:34

import ckeditor.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
import src.apps.settings.fields
import src.models.worck
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryWorck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCategory', models.CharField(max_length=500, verbose_name='Название категории')),
                ('slugCategory', models.CharField(max_length=500, verbose_name='Ссылка на категорию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='contactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSontact', models.CharField(max_length=500, verbose_name='Название пункта с контактами')),
                ('titleSontact', models.CharField(max_length=500, verbose_name='Номер телефона/почта/адрес')),
                ('linkSontact', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('imgSontact', models.CharField(help_text='Ссылка на шрифтовой пак https://fontawesome.ru/', max_length=500, verbose_name='Класс по каторому будет показана иконка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='experienceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearExperience', models.CharField(max_length=500, verbose_name='Год начала карьеры')),
                ('year_old_Experience', models.CharField(blank=True, max_length=500, null=True, verbose_name='Год окончания карьеры')),
                ('postExperience', models.CharField(max_length=500, verbose_name='Название должности')),
                ('companyExperience', models.CharField(max_length=500, verbose_name='Компания')),
                ('textExperience', models.CharField(max_length=500, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='FormsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFormsHome', models.CharField(max_length=200, verbose_name='Имя отправителя')),
                ('emailFormsHome', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('callFormsHome', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10)),
                ('massageFormsHome', models.TextField(verbose_name='Сообщение')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Formsnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComm', models.CharField(max_length=500, verbose_name='Имя')),
                ('emailComm', models.EmailField(max_length=500, verbose_name='Email')),
                ('textComm', models.TextField(verbose_name='Сообщение')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата публиации')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='gallerynews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgnews', models.ImageField(upload_to='photos/news/', verbose_name='Главное изображение записи')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='GallerySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleGallery', models.CharField(max_length=500, verbose_name='Название страницы с фотографиями')),
                ('slugGallery', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Заполняется автоматически')),
                ('dataGallery', models.DateField(default=datetime.date.today, verbose_name='Дата поездки')),
                ('exeptGallery', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('contentGallery', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент для галереи')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='GalleryWorck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img_Worck', models.ImageField(upload_to=src.models.worck.upload_gallery_to, verbose_name='Добавить фото')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
        migrations.CreateModel(
            name='MenuSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLink', models.TextField(default='#', verbose_name='Название ссылки в меню')),
                ('link', models.TextField(default='#', verbose_name='Ссылка на блок на сайте')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='newsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCategory', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slagCategory', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на категорию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='newsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTag', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slagTag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='numberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberTitle', models.CharField(max_length=500, verbose_name='Впишите число или текст')),
                ('numberText', models.CharField(max_length=500, verbose_name='Напишите текст')),
                ('numberDopSimvol', models.CharField(max_length=500, verbose_name='Доп символ после цифры')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='ServicesSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgServices', models.ImageField(upload_to='media/services/', verbose_name='Главное изображение')),
                ('titleServices', models.CharField(max_length=500, verbose_name='Название направления')),
                ('exeptServices', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('contentServices', ckeditor.fields.RichTextField(verbose_name='Контент услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='skillsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleSkills', models.CharField(max_length=500, verbose_name='Название')),
                ('countSkills', models.PositiveIntegerField(verbose_name='Проценты')),
                ('imgSkills', src.apps.settings.fields.SVGImageField(upload_to='photos/home/skill/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='socialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altSocial', models.CharField(max_length=500, verbose_name='Название соц. сети')),
                ('lincSocial', models.URLField(max_length=1000)),
                ('classSocial', models.CharField(help_text='Ссылка на шрифтовой пак https://fontawesome.ru/', max_length=500, verbose_name='Класс по каторому будет показана иконка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgnews', models.ImageField(upload_to='photos/news/', verbose_name='Главное изображение записи')),
                ('datanews', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публиации')),
                ('titlenews', models.CharField(max_length=500, verbose_name='Название статьи')),
                ('slugnews', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Заполняется автоматически')),
                ('contentnews', ckeditor.fields.RichTextField(verbose_name='Контент новости')),
                ('feetbicke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.formsnews', verbose_name='Отзыв')),
                ('gallery', models.ManyToManyField(blank=True, to='models.gallerynews', verbose_name='Галерея фотографий')),
                ('category', models.ManyToManyField(blank=True, to='models.newscategory', verbose_name='Категории статьи')),
                ('tags', models.ManyToManyField(blank=True, to='models.newstag', verbose_name='Теги статьи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='models.gallerysite')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgHome', models.ImageField(upload_to='media/photos/home/', verbose_name='Главное изображение')),
                ('logoSite', models.ImageField(upload_to='media/photos/', verbose_name='Логотип сайта')),
                ('favSite', models.ImageField(upload_to='media/photos/', verbose_name='Фавикон сайта')),
                ('titleHome', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('buttonHeader', models.CharField(max_length=500, verbose_name='Название кнопки')),
                ('sub_titleHome', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('textHome', models.TextField(default='Привет', verbose_name='Подзаголовок')),
                ('copyText', models.CharField(max_length=500, verbose_name='Текст копирайта')),
                ('admin_email', models.EmailField(default='bearcoderr@gmail.com', max_length=254)),
                ('MenuSiteList', models.ManyToManyField(blank=True, to='models.menusite', verbose_name='Меню')),
                ('contactHome', models.ManyToManyField(blank=True, to='models.contactsettings', verbose_name='Контакты')),
                ('experienceHome', models.ManyToManyField(blank=True, to='models.experiencesettings', verbose_name='Вакансия')),
                ('numberlHome', models.ManyToManyField(blank=True, to='models.numbersettings', verbose_name='Номер на главной страницы')),
                ('skillsHome', models.ManyToManyField(blank=True, to='models.skillssettings', verbose_name='Skill')),
                ('socialHome', models.ManyToManyField(blank=True, to='models.socialsettings', verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='WorckSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgWorck_thumb', models.ImageField(upload_to=src.models.worck.upload_worck_to, verbose_name='Миниатюра изображения')),
                ('imgWorck_large', models.ImageField(upload_to=src.models.worck.upload_worck_to, verbose_name='Большое изображение')),
                ('titleWorck', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('exeptWorck', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('clientWorck', models.CharField(blank=True, max_length=500, verbose_name='Клиент')),
                ('dateWorck', models.DateField(default=datetime.date.today, verbose_name='Дата старта работы')),
                ('date_old_Worck', models.DateField(default=datetime.date.today, verbose_name='Дата окончания работы')),
                ('linkWorck', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('desk_title_Worck', models.CharField(max_length=500, verbose_name='Заголовок блока описания')),
                ('contentWorck', ckeditor.fields.RichTextField(verbose_name='Контент работы')),
                ('storyWorck', models.TextField(blank=True, verbose_name='История работы')),
                ('approachWorck', models.TextField(blank=True, verbose_name='Описание что было сделано')),
                ('categoryWorckInfo', models.ManyToManyField(blank=True, to='models.categoryworck', verbose_name='Категория для работы')),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='related_works', to='models.galleryworck')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
