# Generated by Django 5.1.3 on 2024-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysite',
            name='slugGallery',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
