# Generated by Django 5.1.4 on 2024-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='titleHome',
            field=models.CharField(default='Привет', max_length=500, verbose_name='Заголовок'),
        ),
    ]
