# Generated by Django 5.1.4 on 2024-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='feed_not',
            field=models.BooleanField(default=False, verbose_name='Не отправлять в соц сети'),
        ),
    ]
