# Generated by Django 5.1.4 on 2024-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_settings_titlehome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='titleHome',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
    ]
