# Generated by Django 5.1.3 on 2024-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_gallerysite_sluggallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysite',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='models.photo'),
        ),
        migrations.AlterField(
            model_name='gallerysite',
            name='slugGallery',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
    ]
