# Generated by Django 5.1.3 on 2024-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_gallerysite_gallery_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerysite',
            name='exeptGallery',
        ),
        migrations.RemoveField(
            model_name='gallerysite',
            name='gallery_images',
        ),
        migrations.AlterField(
            model_name='gallerysite',
            name='titleGallery',
            field=models.CharField(help_text='Не больше 200 символов', max_length=200, verbose_name='Название страницы с фотографиями'),
        ),
    ]
