# Generated by Django 5.1.3 on 2024-11-21 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_settings_options_remove_settings_menusitelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesettings',
            name='textExperience',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='experiencesettings',
            name='yearExperience',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Год начала карьеры'),
        ),
        migrations.AlterField(
            model_name='experiencesettings',
            name='year_old_Experience',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Год окончания карьеры'),
        ),
    ]
