# Generated by Django 5.1.3 on 2024-11-21 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_experiencesettings_textexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesettings',
            name='year_old_Experience',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Год окончания карьеры'),
        ),
    ]
