# Generated by Django 5.1.3 on 2024-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_experiencesettings_year_old_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesettings',
            name='yearExperience',
            field=models.DateField(default=None, verbose_name='Год начала карьеры'),
        ),
        migrations.AlterField(
            model_name='experiencesettings',
            name='year_old_Experience',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Год окончания карьеры'),
        ),
    ]
