# Generated by Django 5.1.3 on 2024-11-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_remove_news_gallery_remove_news_datanews_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsnews',
            options={'verbose_name': 'Комментарий к новости', 'verbose_name_plural': 'Комментарии к новостям'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='feetbicke',
        ),
        migrations.AddField(
            model_name='formsnews',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.news', verbose_name='Новость'),
            preserve_default=False,
        ),
    ]
