# Generated by Django 5.1.3 on 2024-11-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_formsnews_options_remove_news_feetbicke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsnews',
            name='time_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
