# Generated by Django 5.1.3 on 2024-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_remove_news_category_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='contentCategory',
            field=models.TextField(default=1, max_length=500, verbose_name='Контент категории'),
            preserve_default=False,
        ),
    ]
