# Generated by Django 5.1.3 on 2024-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_newscategory_contentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='countView',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
